foreground         #f8afa2 
background         #160000
cursor #e92715
cursor_text_color #003260

active_tab_foreground     #f8afa2 
active_tab_background     #160000
inactive_tab_foreground   #f8afa2
inactive_tab_background   #160000 

active_border_color   #160000
inactive_border_color #f8afa2 
bell_border_color     #790500

url_color             #f8afa2

color0 #160000
color1 #3587e7
color2 #790500
color3 #f8afa2
color4 #e84d39
color5 #540200
color6 #e92715
color7 #a2c3f9
color8 #942f21
color9 #f8afa2
color10 #fad8d2
color11 #e0b7b1
color12 #e92715
color13 #003260
color14 #e0b7b1
color15 #f8afa2
