foreground         #e5b67b 
background         #181108
cursor #e5b67b
cursor_text_color #574633

active_tab_foreground     #e5b67b 
active_tab_background     #181108
inactive_tab_foreground   #e5b67b
inactive_tab_background   #181108 

active_border_color   #e5b67b
inactive_border_color #5b4017 
bell_border_color     #5b4017

url_color             #e5b67b

color0 #181108
#color1 #a0c4e8
#color2 #574633
#color3 #e5b67b
#color4 #e5b67b
#color5 #e5b67b
color6 #5b4017
color7 #d4bb9e
color8 #574633
#color9 #e5b67b
color10 #e6ded6
#color11 #e5b67b
#color12 #a0c4e8
#color13 #19364d
#color14 #402a08
#color15 #f5dabc
