# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

foreground         #EEE6E1
#background         #1C1A1A
cursor             #A59793

active_tab_foreground     #EEE6E1
active_tab_background     #1C1A1A
inactive_tab_foreground   #1C1A1A
inactive_tab_background   #EEE6E1

active_border_color   #1C1A1A
inactive_border_color #EEE6E1
bell_border_color     #803E2C

#color0 #484544
color1 #592B1F
color2 #803E2C
color3 #B62D33
color4 #B4552E
color5 #AB593E
color6 #D07844
color7 #DFD3CC
color8 #9C948F
color9 #592B1F
color10 #803E2C
color11 #B62D33
color12 #B4552E
color13 #AB593E
color14 #D07844
color15 #DFD3CC

mark1_foreground #D06F36
mark2_foreground #DFB9A3
mark3_foreground #D06F36
