# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

#foreground         #F9F3DF
#background         #110C0B
#cursor             #898A78

#active_tab_foreground     #F9F3DF
#active_tab_background     #110C0B
#inactive_tab_foreground   #110C0B
#inactive_tab_background   #F9F3DF

#active_border_color   #110C0B
#inactive_border_color #F9F3DF
#bell_border_color     #364D25

#color0 #3C3736
color1 #4C2D20
color2 #364D25
color3 #522E20
color4 #6D772F
color5 #946832
#color6 #B29844
#color7 #EEE5C9
#color8 #A7A08D
color9 #522E20
#color10 #3A5327
color11 #875A2A
color12 #747E2B
color13 #AE742E
color14 #EECA5A
color15 #EEE5C9

mark1_foreground #B29536
mark2_foreground #EEDBA1
mark3_foreground #B29536
