[qs-bar-config-v1]
barBorderAlpha=1
barBorderWidth=2
barEdgePaddingLeft=2
barEdgePaddingRight=2
barHeight=36
barMode=bar
barPosition=top
barRadius=20
batteryRadialSize=14
batteryRadialVisible=true
batteryRadialWidth=2
cavaActiveOpacity=0.85
cavaAutoHide=false
cavaBarSpacing=0
cavaGlyphColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaGradientEnabled=false
cavaGradientEndColor=@Variant(\0\0\0\x43\x1\xff\xff\xae\xae\xc4\xc4\xd2\xd2\0\0)
cavaGradientStartColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaInactiveOpacity=0
cavaStyle=dots
cavaTransparentWhenInactive=true
cavaWidth=25
ccGlyph=
glyphSize=12
groupedSpacing=0
infoFontSize=12
infoGlyphSize=12
islandBgOpacityIsland=1
islandBorder=0
islandBorderAlpha=0.22
islandRadius=20
islandSpacing=4
labelFontSize=10
mediaInfoFontSize=10
mediaPadBottom=2
mediaPadLeft=0
mediaPadRight=0
mediaPadTop=2
mediaPlayPauseSize=6
mediaThumbSize=18
modPadH=5
modPadV=2
moduleBgOpacity=0.5
moduleHeight=22
outerMarginBottom=0
outerMarginSide=6
outerMarginTop=2
showBattery=true
showBluetooth=true
showCava=true
showDistro=true
showIdleInhibitor=true
showMediaPlayer=true
showNotifications=true
showOverview=true
showPowerProfiles=true
showRofi=true
showTray=true
showUpdates=true
showWallpaper=true
showWeather=true
showWindow=false
trayIconSz=18
trayItemPadH=1
trayItemPadV=2
trayItemSpacing=0
wsDotActive=󰮯
wsDotEmpty=
wsDotPersistent=󰺕
wsGlyphSize=12
wsIconMode=icon
wsMarginLeft=0
wsMarginRight=0
wsPadBottom=2
wsPadLeft=0
wsPadRight=0
wsPadTop=2
wsSeparatorGlyph=
wsSeparatorPadLeft=2
wsSeparatorPadRight=2
wsSeparatorSize=10
wsSeparators=false
wsSpacing=4
