# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

#foreground         {{ foreground }}
#background         {{ background }}
#cursor             {{ cursor }}

#active_tab_foreground     {{ foreground }}
#active_tab_background     {{ background }}
#inactive_tab_foreground   {{ background }}
#inactive_tab_background   {{ foreground }}

#active_border_color   {{ background }}
#inactive_border_color {{ foreground }}
#bell_border_color     {{ color2 }}

#color0 {{ color0 }}
color1 {{ color4 }}
color2 {{ color10 }}
color3 {{ color5 }}
color4 {{ color9 }}
#color5 {{ color5 }}
#color6 {{ color6 }}
#color7 {{ color7 }}
color8 {{ color1 }}
color9 {{ color9 }}
#color10 {{ color10 }}
color11 {{ color11 }}
color12 {{ color12 }}
color13 {{ color13 }}
color14 {{ color14 }}
color15 {{ color15 }}

mark1_foreground {{ color6 | saturate(0.2) }}
mark2_foreground {{ color7 | saturate(0.2) }}
mark3_foreground {{ color6 | saturate(0.2) }}
