[cc-tabs-v1]
activeTab=0

[cc-weather-loc-v1]
pinnedLat=0
pinnedLon=0
pinnedName=

[cc-wp-picker-v1]
wallpaperDir=/home/king/Pictures/wallpaper

[qs-bar-config-v1]
activeWindowBgOpacity=0
activeWindowMinWidth=23
barBorderAlpha=1
barBorderWidth=2
barEdgePaddingLeft=2
barEdgePaddingRight=2
barHeight=36
barMode=tri
barPosition=top
barRadius=20
batteryRadialSize=14
batteryRadialVisible=true
batteryRadialWidth=2
cavaActiveOpacity=0.85
cavaAutoHide=true
cavaBarSpacing=0
cavaBgOpacity=-1
cavaGlyphColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaGradientEnabled=true
cavaGradientEndColor=@Variant(\0\0\0\x43\x1\xff\xff\xe0\xe0\xb3\xb3\xeb\xeb\0\0)
cavaGradientStartColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaInactiveOpacity=0
cavaStyle=blocks
cavaTransparentWhenInactive=false
cavaWidth=20
ccGlyph=
distroBgOpacity=-1
glyphSize=12
groupedBgOpacity=-1
groupedSpacing=0
infoFontSize=12
infoGlyphSize=12
islandBgOpacityIsland=1
islandBorder=0
islandBorderAlpha=0.22
islandRadius=20
islandSpacing=4
labelFontSize=10
mediaBgOpacity=-1
mediaInfoFontSize=10
mediaPadBottom=2
mediaPadLeft=0
mediaPadRight=0
mediaPadTop=2
mediaPlayPauseSize=6
mediaThumbSize=18
modPadH=5
modPadV=2
moduleBgOpacity=0.5
moduleHeight=22
outerMarginBottom=0
outerMarginSide=4
outerMarginTop=0
showBattery=true
showBluetooth=true
showCava=true
showDistro=true
showIdleInhibitor=true
showMediaPlayer=true
showNotifications=true
showOverview=true
showPowerProfiles=true
showRofi=true
showTray=true
showUpdates=true
showWallpaper=true
showWeather=true
showWindow=true
trayIconSz=18
trayItemPadH=1
trayItemPadV=2
trayItemSpacing=0
ungroupedBgOpacity=-1
wsBgOpacity=-1
wsDotActive=󰮯
wsDotEmpty=
wsDotPersistent=󰺕
wsGlyphSize=12
wsIconMode=icon
wsMarginLeft=0
wsMarginRight=0
wsPadBottom=2
wsPadLeft=0
wsPadRight=0
wsPadTop=2
wsSeparatorGlyph=
wsSeparatorPadLeft=0
wsSeparatorPadRight=4
wsSeparatorSize=8
wsSeparators=true
wsSpacing=4
