[cc-border-colors-v1]
activeBorderColor=#de5110
activeBorderMode=matugen
activeBorderVar=$primary_fixed_dim
inactiveBorderColor=#2a003f
inactiveBorderMode=matugen
inactiveBorderVar=$inverse_primary

[cc-cava-colors-v1]
endMode=matugen
endVar=$primary_container
glyphMode=matugen
glyphVar=$primary
startMode=matugen
startVar=$primary_fixed_dim

[cc-tabs-v1]
activeTab=3

[cc-weather-loc-v1]
pinnedLat=
pinnedLon=
pinnedName=

[cc-wp-picker-v1]
wallpaperDir=

[dock]
autohide=false
autohide_delay=1
layer=top
margin_from_edge=3

[qs-bar-config-v1]
activeWindowBgOpacity=0
activeWindowMinWidth=23
barAutoHide=false
barAutoHideDelay=1
barBorderAlpha=1
barBorderWidth=2
barEdgePaddingLeft=2
barEdgePaddingRight=2
barHeight=36
barMode=bar
barPosition=top
barRadius=20
barRectBgStyle=glass
batteryRadialSize=14
batteryRadialVisible=true
batteryRadialWidth=2
cavaActiveOpacity=1
cavaAutoHide=false
cavaBarHeight=16
cavaBarSpacing=1
cavaBgOpacity=0.7000000000000001
cavaEndCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
cavaEndMode=matugen
cavaEndVar=$primary_fixed_dim
cavaGlyphColor=@Variant(\0\0\0\x43\x1\xff\xff\xf9\xf9\xac\xac\xcb\xcb\0\0)
cavaGlyphCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaGlyphSize=12
cavaGradientEnabled=true
cavaGradientEndColor=@Variant(\0\0\0\x43\x1\xff\xffHH\x93\x93\xa5\xa5\0\0)
cavaGradientStartColor=@Variant(\0\0\0\x43\x1\xff\xff}}\xca\xca\xde\xde\0\0)
cavaInactiveOpacity=0
cavaStartCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\xe5\xe5\xb6\xb6{{\0\0)
cavaStartMode=matugen
cavaStartVar=$tertiary_container
cavaStyle=braille_fill
cavaTransparentWhenInactive=false
cavaWidth=16
ccGlyph=
ccGlyphOpacity=1
distroBgOpacity=0
dockAutoHide=false
dockAutoHideDelay=1
dockLayer=top
dockMargin=3
glyphSize=12
groupedBgOpacity=0
groupedSpacing=0
infoFontSize=12
infoGlyphSize=12
islandBgOpacityIsland=1
islandBgStyle=flat
islandBorder=0
islandBorderAlpha=0
islandRadius=20
islandSpacing=4
labelFontSize=10
launcherBorderRadius=20
launcherBorderWidth=2
launcherFixedTileHeight=78
launcherFixedTileWidth=75
launcherFrameHeight=620
launcherFrameHeightVert=620
launcherFrameWidth=700
launcherFrameWidthVert=700
launcherIconSize=48
launcherInnerBorderWidth=2
launcherInnerPadding=10
launcherListRadius=12
launcherSearchRadius=20
launcherSearchWidth=0.25000000000000006
launcherTextFontSize=14
mediaBgOpacity=0.7000000000000001
mediaInfoFontSize=10
mediaPadBottom=2
mediaPadLeft=0
mediaPadRight=0
mediaPadTop=2
mediaPlayPauseSize=6
mediaThumbSize=16
modPadH=4
modPadV=2
moduleBgOpacity=0.5
moduleHeight=22
outerMarginBottom=0
outerMarginSide=3
outerMarginTop=3
showBattery=true
showBluetooth=true
showCava=true
showDistro=true
showIdleInhibitor=true
showMediaPlayer=true
showNotifications=true
showOverview=true
showPowerProfiles=true
showRofi=true
showTray=true
showUpdates=true
showWallpaper=true
showWeather=true
showWindow=true
startMenuBgOpacity=0.7000000000000001
trayBgOpacity=0.6999999999999997
trayIconSz=20
trayItemPadH=1
trayItemPadV=2
trayItemSpacing=0
ungroupedBgOpacity=0.7000000000000001
wsActiveOpacity=1
wsBgOpacity=0.7000000000000001
wsDotActive=󰮯
wsDotActiveOpacity=1
wsDotEmpty=
wsDotEmptyOpacity=1
wsDotPersistent=󰺕
wsDotPersistentOpacity=1
wsEmptyOpacity=0.6499999999999997
wsGlyphSize=12
wsIconMode=icon
wsIcons="[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]"
wsMarginLeft=0
wsMarginRight=0
wsPadBottom=2
wsPadLeft=0
wsPadRight=0
wsPadTop=2
wsPersistentOpacity=0.8499999999999999
wsSeparatorGlyph=󱗿
wsSeparatorOpacity=0.45
wsSeparatorPadLeft=0
wsSeparatorPadRight=4
wsSeparatorSize=8
wsSeparators=true
wsSpacing=4
