[cc-border-colors-v1]
activeBorderColor=#de5110
activeBorderMode=pywal
activeBorderPywalVar=$color1
activeBorderVar=$inverse_primary
inactiveBorderColor=#2a003f
inactiveBorderMode=pywal
inactiveBorderPywalVar=$color6
inactiveBorderVar=$background

[cc-cava-colors-v1]
endMode=pywal
endPywalVar=$color1
endVar=$inverse_primary
glyphMode=pywal
glyphVar=$primary_fixed_dim
startMode=pywal
startPywalVar=$color6
startVar=$primary_fixed_dim

[cc-tabs-v1]
activeTab=0

[cc-theme-v1]
currentTheme=scheme-fidelity

[cc-weather-loc-v1]
pinnedLat=
pinnedLon=
pinnedName=

[cc-wp-picker-v1]
wallpaperDir=

[dock]
autohide=false
autohide_delay=1
layer=top
margin_from_edge=6

[qs-bar-config-v1]
activeWindowBgOpacity=0
activeWindowMinWidth=23
barAutoHide=false
barAutoHideDelay=1
barBorderAlpha=1
barBorderWidth=2
barEdgePaddingLeft=2
barEdgePaddingRight=2
barHeight=36
barMode=tri
barPosition=top
barRadius=20
barRectBgStyle=glass
batteryRadialSize=14
batteryRadialVisible=true
batteryRadialWidth=2
cavaActiveOpacity=1
cavaAutoHide=false
cavaBarHeight=16
cavaBarSpacing=0.5
cavaBgOpacity=1
cavaEndCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
cavaEndMode=matugen
cavaEndVar=$inverse_primary
cavaGlyphColor=@Variant(\0\0\0\x43\x1\xff\xff\xf9\xf9\xac\xac\xcb\xcb\0\0)
cavaGlyphCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\xe3\xe3\xb0\xb0\xfb\xfb\0\0)
cavaGlyphSize=12
cavaGradientEnabled=true
cavaGradientEndColor=@Variant(\0\0\0\x43\x1\xff\xffHH\x93\x93\xa5\xa5\0\0)
cavaGradientStartColor=@Variant(\0\0\0\x43\x1\xff\xff}}\xca\xca\xde\xde\0\0)
cavaInactiveOpacity=0.05
cavaStartCustomColor=@Variant(\0\0\0\x43\x1\xff\xff\xe3\xe3\xb0\xb0\xfb\xfb\0\0)
cavaStartMode=matugen
cavaStartVar=$primary
cavaStyle=blocks
cavaTransparentWhenInactive=false
cavaWidth=20
ccGlyph=
ccGlyphOpacity=1
distroBgOpacity=0
dockAutoHide=false
dockAutoHideDelay=1
dockLayer=top
dockMargin=6
glyphSize=12
groupedBgOpacity=0
groupedSpacing=0
infoFontSize=12
infoGlyphSize=12
islandBgOpacityIsland=1
islandBgStyle=gradient
islandBorder=0
islandBorderAlpha=0.22
islandRadius=20
islandSpacing=4
labelFontSize=10
launcherBorderRadius=20
launcherBorderWidth=2
launcherFixedTileHeight=78
launcherFixedTileWidth=90
launcherFrameHeight=675
launcherFrameHeightVert=675
launcherFrameWidth=1150
launcherFrameWidthVert=1120
launcherIconSize=48
launcherInnerBorderWidth=1
launcherInnerPadding=10
launcherListRadius=12
launcherSearchRadius=12
launcherSearchWidth=0.2
launcherTextFontSize=11
mediaBgOpacity=1
mediaInfoFontSize=10
mediaPadBottom=2
mediaPadLeft=0
mediaPadRight=0
mediaPadTop=2
mediaPlayPauseSize=6
mediaThumbSize=20
modPadH=5
modPadV=2
moduleBgOpacity=0.5
moduleHeight=22
outerMarginBottom=0
outerMarginSide=2
outerMarginTop=4
showBattery=true
showBluetooth=true
showCava=true
showDistro=true
showIdleInhibitor=true
showMediaPlayer=true
showNotifications=true
showOverview=true
showPowerProfiles=true
showRofi=true
showTray=true
showUpdates=true
showWallpaper=true
showWeather=true
showWindow=true
startMenuBgOpacity=1
trayBgOpacity=0
trayIconSz=20
trayItemPadH=1
trayItemPadV=2
trayItemSpacing=0
ungroupedBgOpacity=1
wsActiveOpacity=1
wsBgOpacity=1
wsDotActive=󰮯
wsDotActiveOpacity=1
wsDotEmpty=
wsDotEmptyOpacity=1
wsDotPersistent=󰺕
wsDotPersistentOpacity=1
wsEmptyOpacity=0.55
wsGlyphSize=12
wsIconMode=icon
wsIcons="[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]"
wsMarginLeft=0
wsMarginRight=0
wsPadBottom=2
wsPadLeft=0
wsPadRight=0
wsPadTop=2
wsPersistentOpacity=0.7
wsSeparatorGlyph=󱗿
wsSeparatorOpacity=0.44999999999999996
wsSeparatorPadLeft=0
wsSeparatorPadRight=4
wsSeparatorSize=8
wsSeparators=true
wsSpacing=4
