-- Generated by matugen from ~/.config/matugen/templates/hyprland-colors.lua
-- HyprCandyPlus Hyprland Lua color bridge.
-- Exposes each matugen color as both a global Lua variable and as matugen.<name>.

matugen = matugen or {}


background = "rgba(000000ff)"
matugen.background = background

error = "rgba(f8afa6ff)"
matugen.error = error

error_container = "rgba(9d1b19ff)"
matugen.error_container = error_container

inverse_on_surface = "rgba(1d1b18ff)"
matugen.inverse_on_surface = inverse_on_surface

inverse_primary = "rgba(583c16ff)"
matugen.inverse_primary = inverse_primary

inverse_surface = "rgba(e6ded6ff)"
matugen.inverse_surface = inverse_surface

on_background = "rgba(e6ded6ff)"
matugen.on_background = on_background

on_error = "rgba(160000ff)"
matugen.on_error = on_error

on_error_container = "rgba(ffffffff)"
matugen.on_error_container = on_error_container

on_primary = "rgba(100900ff)"
matugen.on_primary = on_primary

on_primary_container = "rgba(000000ff)"
matugen.on_primary_container = on_primary_container

on_primary_fixed = "rgba(000000ff)"
matugen.on_primary_fixed = on_primary_fixed

on_primary_fixed_variant = "rgba(3e2907ff)"
matugen.on_primary_fixed_variant = on_primary_fixed_variant

on_secondary = "rgba(130d06ff)"
matugen.on_secondary = on_secondary

on_secondary_container = "rgba(ffffffff)"
matugen.on_secondary_container = on_secondary_container

on_secondary_fixed = "rgba(000000ff)"
matugen.on_secondary_fixed = on_secondary_fixed

on_secondary_fixed_variant = "rgba(3b2f1fff)"
matugen.on_secondary_fixed_variant = on_secondary_fixed_variant

on_surface = "rgba(ece2dbff)"
matugen.on_surface = on_surface

on_surface_variant = "rgba(ccbeafff)"
matugen.on_surface_variant = on_surface_variant

on_tertiary = "rgba(050600ff)"
matugen.on_tertiary = on_tertiary

on_tertiary_container = "rgba(000000ff)"
matugen.on_tertiary_container = on_tertiary_container

on_tertiary_fixed = "rgba(000000ff)"
matugen.on_tertiary_fixed = on_tertiary_fixed

on_tertiary_fixed_variant = "rgba(292d0dff)"
matugen.on_tertiary_fixed_variant = on_tertiary_fixed_variant

outline = "rgba(95897cff)"
matugen.outline = outline

outline_variant = "rgba(5c5348ff)"
matugen.outline_variant = outline_variant

primary = "rgba(e5b67bff)"
matugen.primary = primary

primary_container = "rgba(a37c48ff)"
matugen.primary_container = primary_container

primary_fixed = "rgba(fad9b2ff)"
matugen.primary_fixed = primary_fixed

primary_fixed_dim = "rgba(e5b67bff)"
matugen.primary_fixed_dim = primary_fixed_dim

scrim = "rgba(000000ff)"
matugen.scrim = scrim

secondary = "rgba(d4bb9eff)"
matugen.secondary = secondary

secondary_container = "rgba(61503bff)"
matugen.secondary_container = secondary_container

secondary_fixed = "rgba(f5dabcff)"
matugen.secondary_fixed = secondary_fixed

secondary_fixed_dim = "rgba(d4bb9eff)"
matugen.secondary_fixed_dim = secondary_fixed_dim

shadow = "rgba(000000ff)"
matugen.shadow = shadow

source_color = "rgba(a57c44ff)"
matugen.source_color = source_color

surface = "rgba(000000ff)"
matugen.surface = surface

surface_bright = "rgba(2d2926ff)"
matugen.surface_bright = surface_bright

surface_container = "rgba(0d0b0aff)"
matugen.surface_container = surface_container

surface_container_high = "rgba(191715ff)"
matugen.surface_container_high = surface_container_high

surface_container_highest = "rgba(26231fff)"
matugen.surface_container_highest = surface_container_highest

surface_container_low = "rgba(050404ff)"
matugen.surface_container_low = surface_container_low

surface_container_lowest = "rgba(000000ff)"
matugen.surface_container_lowest = surface_container_lowest

surface_dim = "rgba(000000ff)"
matugen.surface_dim = surface_dim

surface_tint = "rgba(e5b67bff)"
matugen.surface_tint = surface_tint

surface_variant = "rgba(39322aff)"
matugen.surface_variant = surface_variant

tertiary = "rgba(bac385ff)"
matugen.tertiary = tertiary

tertiary_container = "rgba(7e8650ff)"
matugen.tertiary_container = tertiary_container

tertiary_fixed = "rgba(dae2a1ff)"
matugen.tertiary_fixed = tertiary_fixed

tertiary_fixed_dim = "rgba(bac385ff)"
matugen.tertiary_fixed_dim = tertiary_fixed_dim


return matugen
