-- HyprCandyPlus mutable Hyprland Lua state.
-- Generated by Quickshell Control Center and helper scripts; edit sliders instead of this file.
-- Loaded after hyprviz.lua, so keys below override migrated defaults.

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 12,
        border_size = 3,
        col = {
            active_border = color6,
        },
    },
    decoration = {
        rounding = 10,
        active_opacity = 0.85,
        inactive_opacity = 0.85,
        blur = {
            size = 1,
            passes = 5,
            xray = true,
        },
    },
})

hl.layer_rule({
    match = {
        namespace = ".*",
    },
    xray = true,
})

return true
