use_default_settings: true

general:
  debug: false
  instance_name: "HyprCandy SearXNG"

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "hyprcandy-permanent-local-secret-key-3f98a21b44c8"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  formats:
    - html
    - json
