-- Generated by pywal from ~/.config/wal/templates/hyprland-colors.lua
-- HyprCandyPlus Hyprland Lua color bridge.
-- This file intentionally exposes both global names and a pywal table so
-- existing HyprCandy variable selections can migrate from $colorN to colorN.

pywal = pywal or {}

local function rgba(hex)
    hex = tostring(hex or ""):gsub("#", "")
    return "rgba(" .. hex .. "ff)"
end

foreground = rgba("{foreground}")
background = rgba("{background}")
cursor = rgba("{cursor}")

color0 = rgba("{color0}")
color1 = rgba("{color1}")
color2 = rgba("{color2}")
color3 = rgba("{color3}")
color4 = rgba("{color4}")
color5 = rgba("{color5}")
color6 = rgba("{color6}")
color7 = rgba("{color7}")
color8 = rgba("{color8}")
color9 = rgba("{color9}")
color10 = rgba("{color10}")
color11 = rgba("{color11}")
color12 = rgba("{color12}")
color13 = rgba("{color13}")
color14 = rgba("{color14}")
color15 = rgba("{color15}")

pywal.foreground = foreground
pywal.background = background
pywal.cursor = cursor
pywal.color0 = color0
pywal.color1 = color1
pywal.color2 = color2
pywal.color3 = color3
pywal.color4 = color4
pywal.color5 = color5
pywal.color6 = color6
pywal.color7 = color7
pywal.color8 = color8
pywal.color9 = color9
pywal.color10 = color10
pywal.color11 = color11
pywal.color12 = color12
pywal.color13 = color13
pywal.color14 = color14
pywal.color15 = color15

return pywal
