-- Generated by matugen from ~/.config/matugen/templates/hyprland-colors.lua
-- HyprCandyPlus Hyprland Lua color bridge.
-- Exposes each matugen color as both a global Lua variable and as matugen.<name>.

matugen = matugen or {}

<* for name, value in colors *>
{{name}} = "rgba({{value.default.hex_stripped}}ff)"
matugen.{{name}} = {{name}}
<* endfor *>

return matugen
